### ISSUE TITLE
Mod Application

### ISSUE THREAD

**Issue by Chucky2sRevenge** [kenneththomas/cechat-politica#10]
Username: Poop
Preferred name: Poop
Age: Poop
Gender: Poop
Height: Poop
Ethnicity: Poop
Useful skills: Poop
Previous employment: Poop
Your biggest weakness: Poop
Why you feel you are right for this job: Poop

Signature: Poop

**Comment by Pwnlamesa** [comment]
Status: Rejected

-Heyzeus

**Comment by Albireos** [comment]
Username: Armando#420
Preferred name: Armando
Age: N/A
Gender: N/A
Height: N/A
Ethnicity: N/A
Useful skills: N/A
Previous employment: N/A
Your biggest weakness: N/A
Why you feel you are right for this job: N/A

Signature: :^)

**Comment by Pwnlamesa** [comment]
All applications need to be posted as a new issue.

Please follow all directions as stated in the original post, thank you.

-Heyzeus

**Comment by Albireos** [comment]
**New Issue**
Username: Armando#420
Preferred name: Armando
Age: N/A
Gender: N/A
Height: N/A
Ethnicity: N/A
Useful skills: N/A
Previous employment: N/A
Your biggest weakness: N/A
Why you feel you are right for this job: N/A

Signature: :^)

**Comment by kenneththomas** [comment]
no
