### ISSUE TITLE
Ban Report - Barinade88

### ISSUE THREAD

**Issue by Pwnlamesa** [kenneththomas/cechat-politica#13]
User: Barinade88
Date of ban: Monday, October 16, 2017 at 9:42 PM
Reason: Harassment of a moderator through private messaging
Moderator: Heyzeus

**Scenario:**
- [Barinade88] posted two pictures in the safe-for-neets chat, which prompted deletion of the pictures and a temporary removal of access to the room.
- [Barinade88] decides to private message [Heyzeus] web links to shocking images, as assumed by the URL descriptions (key terms such as "maggot-infested" and "ribbon-penis").
- [Barinade88] gets warned by [Heyzeus] to stop, which prompted the following from [Barinade88]: "ooh a threat", "more pics incoming den" "damn im still not banned yet - gotta up it" and an additional two URLs sent through private message to [Heyzeus]. (1.)
- [Barinade88] proceeds to get banned by [Heyzeus]. (2.)

(1.)
![bari1](https://user-images.githubusercontent.com/32789316/31661304-33af9790-b308-11e7-90d9-fa99ca65a847.png)
(2.)
 ![bari2](https://user-images.githubusercontent.com/32789316/31661318-42eb5e7e-b308-11e7-8233-38f878275b8b.png)

**Psychiatric analysis:**
- Possible intoxication from alcohol during time of the incident
- Possible feelings of insecurity due to the addition of [TK] to the chat room early September

Signed: - Heyzeus

**Comment by kenneththomas** [comment]
xd
