### ISSUE TITLE
job application

### ISSUE THREAD

**Issue by doggydoggydingdong** [kenneththomas/cechat-politica#14]
Username: wlofaubro
Preferred name: wlof
Age: 23
Gender: male
Height: 5'11
Ethnicity: black and jewish
Useful skills: professional snitch
Previous employment: professional snitch
Your biggest weakness: black and jewish
Why you feel you are right for this job: i am a professional snitch

Signature: wlofaubro

**Comment by Albireos** [comment]
wow this is cyborg bullying

**Comment by kenneththomas** [comment]
i think he filled this out himself

**Comment by kenneththomas** [comment]
approved
