### ISSUE TITLE
Request: #Barinade channel

### ISSUE THREAD

**Issue by MrMallard** [kenneththomas/cechat-politica#15]
DP is playing a VN, and he named the main character after Barinade. It's really funny, the MC is kind of a loser - I would like to request a new channel for DP to chronicle this adventure, so that his screenshots are not lost to the passage of time in the main chat, or lost among the t!dailies and other miscellaneous requests in #barco.

Whether it be a locked chat like NSFW or an open channel for anyone to follow the adventure, I would love a #Barinade channel for this kind of quality content.

**Comment by kenneththomas** [comment]
no
