### ISSUE TITLE
Make safe space and actual safe space

### ISSUE THREAD

**Issue by Albireos** [kenneththomas/cechat-politica#19]
so . can't join

**Comment by Pwnlamesa** [comment]
t. Heyzeus

**Comment by kenneththomas** [comment]
who is .

**Comment by kenneththomas** [comment]
Dear Albireos,

This request cannot be actioned as it is unclear who "." is.

Kindly do the needful and please advise who "." is or this ticket will be marked as "closed"

**Comment by kenneththomas** [comment]
Ticket submitted did not do the needful, and certainly not kindly.
