### ISSUE TITLE
Display picture...

### ISSUE THREAD

**Issue by Flamazide** [kenneththomas/cechat-politica#2]
Armando now has a cat with "Heterochromia iridium" (I googled how to spell that!) for his display picture. While it does make sense given the name "Albireos" that he has adopted in some places, I feel that the name is completely dishonest as Armando does not in fact own a cat. Armando actually owns a dog. Cats are, and have always been, the sworn enemy of canines. When you take a animal home to live with you as your pet and care for it they are practically a part of your family. You cannot have the primary nemesis of one of your family remembers as your icon, an avatar/representation of yourself. That is a complete disrespect to Armando's dog. I demand that Armando's picture be changed in their behalf.

Sincerely, Flam A. "9 Inches" Zide

**Comment by kenneththomas** [comment]
I liked the avatar when Armando had the dog on the stove.

**Comment by WahhWahh** [comment]
i miss the breez dog filter avatar

**Comment by kenneththomas** [comment]
armando has the dog on the stove avatar now so this request is donezo

**Comment by DaveJangler** [comment]
who is dog
