### ISSUE TITLE
film club 6/22

### ISSUE THREAD

**Issue by kenneththomas** [kenneththomas/cechat-politica#26]
fast n furious tokyo drift

**Comment by kenneththomas** [comment]
midnight rst

**Comment by kenneththomas** [comment]
Please join us for Film Club @ 12PM RST, for a viewing of Fast n' Furious San (That's 3 in Japanese) Tokyo Drift: https://www.rabb.it/s/eklyvf

**Comment by DaveJangler** [comment]
No
