### ISSUE TITLE
I want a text channel for shy people!

### ISSUE THREAD

**Issue by WahhWahh** [kenneththomas/cechat-politica#3]
Dear chat friends,
I would like to wish for a text channel (or whatever we call it) for shy people. That includes me (Music), kbelf, teef and Barinade as of right now. If someone else pretends to be shy, then it's simply not true. I just want a safe place to express myself without being judged, and I can only do that around other shy people. Thank you for listening and have a nice day.

Music The Shy one

**Comment by kenneththomas** [comment]
Request is approved, please allow until 8pm EST for scheduled work to be completed.

**Comment by kenneththomas** [comment]
this is delayed due to me eating delicious barbecue food

**Comment by kenneththomas** [comment]
channel has been created
