### ISSUE TITLE
Invite Pete Back 

### ISSUE THREAD

**Issue by WildPete** [kenneththomas/cechat-politica#44]
but im still blocking bari so his bad posts dont show up at work and it doesnt fire me

**Comment by Albireos** [comment]
Barinade is legit on timeout LMAO.

**Comment by Albireos** [comment]
[https://cdn.discordapp.com/attachments/273251775933579264/961116700110094336/unknown.png](url)

**Comment by Albireos** [comment]
![](https://cdn.discordapp.com/attachments/273251775933579264/961116700110094336/unknown.png)

**Comment by Albireos** [comment]
https://discord.gg/YDEbdf8e
