### ISSUE TITLE
Please to remove me from role @iphone siccy

### ISSUE THREAD

**Issue by hortanz** [kenneththomas/cechat-politica#47]
Please to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccyPlease to remove me from role @iphone siccy put siccy back in

**Comment by BokChoiFresh** [comment]
User Hiten has been removed from this role. Unable to place user Hikachu back into role. Ticket should be resolved @kenneththomas
