### ISSUE TITLE
:Butthink:

### ISSUE THREAD

**Issue by WildPete** [kenneththomas/cechat-politica#51]

**Comment by Albireos** [comment]
Asking to get banned.

**Comment by Y-Manuhts** [comment]
Hey @WildPete if it's not against Github's TOS to say, kill yourself.
If it is against the TOS to say, then please consider killing yourself 👍

**Comment by WildPete** [comment]
There is no rule listed that I have violated.  I demand to be removed from timeout.

**Comment by WildPete** [comment]
![image](https://user-images.githubusercontent.com/83772974/197365182-0ffea197-4968-4469-bc49-db25a783d9b6.png)

**Comment by Albireos** [comment]
> 

https://github.com/kenneththomas/thecondo-politica/blob/master/rules.txt

Check line 37

> I. The "butthink" emoji is not permitted to be used in chat. This emoji should not be crossposted from another server. Any admin found adding the butthink emoji to thecondo will lose admin privileges.

**Comment by ItsHikachu** [comment]
is rick moranis dead?

**Comment by ItsHikachu** [comment]
or just his career

**Comment by WildPete** [comment]
> > 
> 
> https://github.com/kenneththomas/thecondo-politica/blob/master/rules.txt
> 
> Check line 37
> 
> > I. The "butthink" emoji is not permitted to be used in chat. This emoji should not be crossposted from another server. Any admin found adding the butthink emoji to thecondo will lose admin privileges.

I don't read the rules I break them.  Now remove me or armando will suffer.

**Comment by Albireos** [comment]
> > > 
> > 
> > 
> > https://github.com/kenneththomas/thecondo-politica/blob/master/rules.txt
> > Check line 37
> > > I. The "butthink" emoji is not permitted to be used in chat. This emoji should not be crossposted from another server. Any admin found adding the butthink emoji to thecondo will lose admin privileges.
> 
> I don't read the rules I break them. Now remove me or armando will suffer.

Line 21

> A. Be nice to Armando

**Comment by WildPete** [comment]
Okay invite me back when yall decide to stop fucking with me.  In the meantime I'd keep an eye on your base.

**Comment by ItsHikachu** [comment]
Please remove me from the fake incel role thx

**Comment by kenneththomas** [comment]
pm mf m
