### ISSUE TITLE
New sticker request 2/5/2024

### ISSUE THREAD

**Issue by Pwnlamesa** [kenneththomas/cechat-politica#66]
Hello,

Please add this as a new sticker with the sticker name "slightlysmugpepe"

![272](https://github.com/kenneththomas/thecondo-politica/assets/32789316/e18771a1-dc6f-4b5e-b8fe-8ebe6499ad21)

Thank you,
-Tommy

**Comment by Pwnlamesa** [comment]
bump

**Comment by kenneththomas** [comment]
ack
