### ISSUE TITLE
New sticker request 6/24/2024

### ISSUE THREAD

**Issue by Pwnlamesa** [kenneththomas/cechat-politica#73]
Hello,

Please add a new sticker to gato with the name "diatomaceous earth" or a suitable equivalent if that name is too long.

![Untitled](https://github.com/kenneththomas/thecondo-politica/assets/32789316/1a03895f-5a0a-4598-be17-4959a588833a)

Thanks,
-Tommy

**Comment by Pwnlamesa** [comment]
bump

**Comment by kenneththomas** [comment]
ack

**Comment by kenneththomas** [comment]
complete
